### ISSUE TITLE
Working towards a first demo

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#1]
Objectives:

- [x] autonomous navigation including coordinator
- [x] SPENCER person tracking shown on screen working
- [ ] ideally: one pick and place operation (4 topological places where pallets can be, task is e.g. pick from place A, deliver to place C)

Steps:
- [x] installed from released packages
- [x] remote administration working
- [x] sensor configuration & powering
- [x] alienware powering
- [x] mapping of INB lab and atrium

**Comment by MFernandezCarmona** [comment]
About remote administration working.
First, is there any tutorial about how to set up and test avocado on it?
Forklift Alienware is currently connected to "unifi-lcas", but I failed to ssh it from my pc when it was on. Shall we use other wifi network with broader coverage?

**Comment by marc-hanheide** [comment]
That's odd. Usually the unifi-lcas works well. What's the IP address?

**Comment by MFernandezCarmona** [comment]
10.5.32.133 (right now it's down)

**Comment by MFernandezCarmona** [comment]
Remote administration:
Mostly works. Keep the pc's on to ensure that the DHCP lease does not expire and they stick to the IP on Guacamole.
cititruck-1: 10.5.32.137

For some reason, unifi-lcas network does not acknowledge our id for the cititruck.

**Comment by MFernandezCarmona** [comment]
SPENCER person tracking:
Need proper tfs (kinect, lasers, odom) to make it work

**Comment by MFernandezCarmona** [comment]
This is long done. However, pick demo is unknown to me and it shouldn't. I'll take note of it to reproduce it after MS3
