### ISSUE TITLE
How to include a dependency to a tar file on a web?

### ISSUE THREAD

**Issue by MFernandezCarmona** [LCAS/iliad#11]
twist_controller package is failing to compile because it requires canlib.h to be installed. However, that lib can be only installed downloading and compiling a tar file from here:

http://canlandbucket.s3-website-eu-west-1.amazonaws.com/productionResourcesFiles/d956a793-9e4d-4384-a5e9-3e2428fcfd40/linuxcan.tar.gz

Options?

**Comment by marc-hanheide** [comment]
Is this part of the kvaser can lib? If so, then it is already released and in Ros deb

https://github.com/LCAS/rosdistro/blob/master/rosdep/lcas.yaml#L32

**Comment by marc-hanheide** [comment]
So you can try to simply depend on that

**Comment by MFernandezCarmona** [comment]
Yes that one. But is it kvaser-libcan instead of kvaser_libcan?

**Comment by MFernandezCarmona** [comment]
Great! done
