### ISSUE TITLE
tidy up repo and prepare first release for MS3 demo

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#28]
- [x] remove outdated/unused packages (keep in `deprecated` branch)
- [x] ensure maintainers are set
- [x] prefix packages with `iliad` if they have ambiguous names for packages

I suggest creating a new branch `tidy` and test via PR builds.

**Comment by MFernandezCarmona** [comment]
See https://github.com/LCAS/iliad/pull/30

**Comment by MFernandezCarmona** [comment]
Outdated/experimental moved to repo https://github.com/LCAS/iliad_experimental.
Rest is also done.
