### ISSUE TITLE
MS3 demo preparations

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#29]
- [x] visualisation of QTC / QSR constraints in Rviz (maybe for Laurence)
- [x] implement speed contraints according to MS3 demo script
- [x] release all relevant components, including the "hacked" 3D detector models.

**Comment by MFernandezCarmona** [comment]
1) Working on that
2) Need to create an specific demo for it and add to `iliad_metapackage`. Could also be used to show 1)
3) That is basically releasing `iliad` and `iliad_metapackage`, right? The first one I think is automatic, the second one, I don't know.

**Comment by MFernandezCarmona** [comment]
Updates:
- Visualization was done in `QTCPlot.py`. See `ms3.launch` in `iliad_dynamic_constraints`.
- Speed constraints can be set using a gui. See `iliad_dynamic_constraints/launch/slider_gui.launch`
- Tunned 3d detectors use configurations from  `iliad_launch_system` and released detectors. The rest is part of `iliad` package, and will be released as soon as we move all to `master` branch.

Further developments will be done in more specific issues
