### ISSUE TITLE
Prepare point and click demo in INB lab

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#31]

**Comment by marc-hanheide** [comment]
So, the current demo is not using NDT... @MFernandezCarmona to look into this with Daniel.

**Comment by marc-hanheide** [comment]
@laurencejbelliott and @MFernandezCarmona to work on it to fix it.

**Comment by MFernandezCarmona** [comment]
Tasks:
- Fix Velodyne (loose cable fixed)
- Fix localization (using new code from Daniel)
- Fix human tracker (current choices: UoL and ILIAD trackers): We use ILIAD but we need a version with Velodyne included. 
- Find sweet spots (where navigation tends to work for tests): Done:
```
  frame_id: "map_laser2d"

Start position: 
      x: 1.5
      y: -0.5
    orientation: 
      z: 0.408241534923
      w: 0.912873950315
---
End position: 
    x: 4.5
    y: 3.5
  orientation: 
    z: 0.408241534923
    w: 0.912873950315
```
