### ISSUE TITLE
integrate 3D person tracker

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#32]
as the BOSCH 3D tracker is very resource-hungry, we shall try our own detector system as use at NCFM. 

Tests:

- [x] check if BOSCH tracker is indeed not working on the current hardware
- [x] make an assessment of the false positive and false negative of our detector (qualitatively)

**Comment by MFernandezCarmona** [comment]
- BOSH tracker:
Disabling `HAS_GPU` option makes it work reasonably. However, it does not have Velodyne integrated. As a consequence, only 180 deg FOV.
- UoL Tracker: checking

**Comment by MFernandezCarmona** [comment]
Both trackers are up and running. We will focus on UoL tracker as it has a wider FOV. However, if Timm gives us a working setup to integrate velodyne tracker in spencer pipeline, we can revisit this decission.

**Comment by MFernandezCarmona** [comment]
Change `object3d_detector` to `lidar_object_detection_release`.
ROS package: `lidar_object_detection` 
#apt   ros-kinetic-lidar-object-detection
*WE WILL USE* source at https://github.com/LCAS/lidar_object_detection_release because released is older.

**Comment by MFernandezCarmona** [comment]
Create a new map based on the laser map to define the only active area.

**Comment by MFernandezCarmona** [comment]
Ok. Now we can switch from `object3d_detector` to `lidar_object_detection` by setting a flag in `people_3d.launch`. By default is using `lidar_object_detection` but if you want to go back, just set `use_new` to `false`

**Comment by MFernandezCarmona** [comment]
Static map has been replaced by a new "active area map". We are ready to test again.
