### ISSUE TITLE
Power Supply & Hardware Setup

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#4]
* Orebru is using this one for their embedded PC on the forklift: http://www.mini-box.com/M4-ATX We might need another solution.
* Velodyne can be powered from the banana sockets on board (24V, 2A)
* We are looking for ~19.5V 10A stabilised power supply, ask Jason for advice
* Talk to Henrik how to wire it to batteries
* mounting of velodyne:  Velodyne upside down hanging from the top shelf in the cititruck so that it is centered between the top and middle shelf
* Kinect v2 to go on top-shelf, usually pointing backwards (ie towards the forks), but we should mount it so it can be turned around
* A `tf` transform for those sensors needs to be implemented (i believe it isn't yet)
* make sure it complied with the simulated version, too.

Use our INB forklift as the testing platform, but bear in mind, we have another one at NCFM, which shall be a clone.

**Comment by MFernandezCarmona** [comment]
I was checking Kinect 2 power specs and I found the following:
- It requires 12V@2.64A.
- It is not fully supported in linux&ROS.
- It is discontinued from production.

Are we 100% we want to install it anyway?

**Comment by marc-hanheide** [comment]
please discuss on #sensor channel on Slack!

**Comment by MFernandezCarmona** [comment]
Moving

**Comment by MFernandezCarmona** [comment]
Updates:
- Jason is looking for proper dc/dc converters for the Alienware & Kinect V2.
- Kinnect 2 works with power & USB3 mod: no need for Microsoft pc converter now.
- DC/DC converter will be most likely directly connected to the batteries (like previous).
- Uppermost shelf will be removed, as PC will be inside the chassis, at the top with DC/DC converters. There is plenty of space there.
- Velodine will be mounted on top of current laser sensor, using a V shape like in Rusty, avoiding most of oclussions.
- Kinnect will be mounted on top of velodine, like fish eye cameras are in rusty/flobot.

**Comment by marc-hanheide** [comment]
Regarding the mounting: Can't we mount the velodyne from above, not causing any occlusion to the KM laser? And, wouldn't it better to mount the Kinect on the top shelf (even simply with cable tights or similar)? Just want to open the discussion @gcielniak @tduckett @sergimolina

**Comment by sergimolina** [comment]
The thing is, there are always 2 occlusions for the KM laser, no matter we leave the default shelf or the v-shape frame. However, the good thing about the v-shape frame is that it doesn't produce any occlusion for the velodyne, as the opposite of the default shelf (thats what I understand from mounting from above).

**Comment by marc-hanheide** [comment]
As usual, you are wiser than me...

**Comment by MFernandezCarmona** [comment]
Long done. Closing
