### ISSUE TITLE
test teb and dwa on robot

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#5]

**Comment by MFernandezCarmona** [comment]
Tested in simulation.
- TEB planner works but each iteration produces very different paths. Robot takes some time changing its steering after each new plan, which again triggers new path requests, thus big oscillations.
- DWA is working ok, and what is more, our human aware dwa has been tested on simulation.
I don't know if it's worth trying it on the real robot dough.

**Comment by MFernandezCarmona** [comment]
This is now being done at https://github.com/LCAS/iliad/tree/master/iliad_local_planner. Still under development, as we want to forward the local path to MPC, instead of overriding it as before.
