### ISSUE TITLE
translator from SPENCER format to use in HRSI

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#8]
we need to transform data from SPENCER format to [`bayes_people_tracker/PeopleTracker`](https://github.com/strands-project/strands_perception_people/blob/kinetic-devel/bayes_people_tracker/msg/PeopleTracker.msg). 

Then, we should have a simple launch file, that fires up Spencer People Tracking and runs https://github.com/strands-project/strands_hri/blob/kinetic-devel/hrsi_representation/scripts/online_qtc_creator.py then we should see the QTC state for any people that are detected.

**Comment by marc-hanheide** [comment]
@MFernandezCarmona to assist

**Comment by marc-hanheide** [comment]
The best is probably to create a new package `iliad_human_local_navigation`, to include the new nodes and the respective launch files.
This package will naturally depend on spencer, and strands_perception_people and strands_hrsi, which is fine.

**Comment by MFernandezCarmona** [comment]
I will modify current iliad simulation using spencer person tracking  to use our human aware dwa planner. It won't work but will provide @tejaspp all the pieces for his data format converter.
Here is the simulation, for the record:
https://gitsvn-nt.oru.se/iliad/software/iliad_human_perception/tree/master/iliad_human_perception_launch

**Comment by MFernandezCarmona** [comment]
Done in iliad_human_local_navigation spencer_to_bayes.py. Reverse included in QSR in method bayes2spencer
