### ISSUE TITLE
create an iliad_launch package

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/iliad#9]
that contains the launch files for all the different sub-systems:

* `core`, contains main driver and sensors
* `sim_core`, which does the same as core for simulation
* `navigation`
* `people_perception`

For those, please consider writing TMule configs, see 
https://github.com/marc-hanheide/TMuLe

**Comment by MFernandezCarmona** [comment]
This turned into https://gitsvn-nt.oru.se/iliad/software/iliad_metapackage
